version: 2
jobs:
  build:
      docker:
        - image: circleci/node:8.11
        - image: circleci/postgres:latest

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm install
        - run: npm init:db
