version: 2
jobs:
  build:
      docker:
       - image: circleci/node:8.11
         environment:
            PGHOST: localhost
            PGPORT: '5432'
            PGDATABASE: circle_test
            PGUSER: circleuser
            PGPASSWORD: circlepassword
            JWT_SECRET: secret
       - image: circleci/postgres:latest
         environment:
           POSTGRES_USER: circleuser
           POSTGRES_DB: circle_test
           POSTGRES_PASSWORD: circlepassword

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm install
        - run: npm run init:db
        - run:
            name: Run mocha tests
            environment:
              NODE_ENV: test
            command: npm run test
